### ISSUE TITLE
Waiting for SeedSync service to respond

### ISSUE THREAD

**Issue by lkuey** [ipsingh06/seedsync#134]
Hi there - and Merry Christmas. 

I've struggled to install SeedSync via Unraid and hope to get some advice. Apologies ahead of time as I am a relative noob user.

I was recommended to use LFTP by my seedbox provider as an alternative to Syncthing, which has become somewhat of a bottleneck in transferring files from my seedbox to my Unraid server. I had some initial issues in installing SeedSync, which was fixed by adding '-u 99:100' as an extra parameter in the configuration. I am now able to open SeedSync via the WebGUI but unfortunately although I can see the full GUI, I am unable to use it whatsoever as it says 'Waiting for SeedSync service to respond'. 

The only thing I could pick up from logs is this:

`2023-12-25 22:16:13,608 - ERROR - seedsync (MainProcess/MainThread) - Config is incomplete`

I can't see what part of the configuration remains incomplete. I've attached an image. 

Would anyone be able to please advise? 
<img width="1017" alt="Screenshot 2023-12-25 at 22 29 23" src="https://github.com/ipsingh06/seedsync/assets/81826672/39fd7eed-4364-4707-992c-3339793f76a8">
<img width="1063" alt="Screenshot 2023-12-25 at 22 30 28" src="https://github.com/ipsingh06/seedsync/assets/81826672/0c017e87-0e20-4281-b7e4-46163b618842">

**Comment by quadcom** [comment]
Go to the settings inside of the SS UI and configure your connection to
your seedbox.

**Comment by lkuey** [comment]
> Go to the settings inside of the SS UI and configure your connection to your seedbox.
> […](#)

Really appreciate you getting back to me so quickly with a simple answer.

 Accessing the Unraid GUI via a different device on my network, it greyed out all the Seedsync options. When I tried accessing via the local Unraid machine, it worked. My mistake. 

Thanks again.
