### ISSUE TITLE
Permissions on downloaded content

### ISSUE THREAD

**Issue by AquaRelliux** [ipsingh06/seedsync#19]
I added this docker container to my unraid server and it works great. However I do have a small issue. And that is that when the file is downloaded permissions are only given to root since it runs the container. Therefor I can't move files from the share that I have for this machine only copy them Is there a way to make the container set permissions on files after download is complete?

**Comment by ipsingh06** [comment]
This issue has been fixed in the latest version v0.7.0, please give it a try!

It will use the default user to run the docker image. If you wish to use a non-default user, then follow the instructions at https://github.com/ipsingh06/seedsync#-docker-image-on-linux
