### ISSUE TITLE
Remote Scan Errors

### ISSUE THREAD

**Issue by hxcadam** [ipsingh06/seedsync#2]
I get random remote scan errors once a day which makes me have to restart Seedsync for it to start scanning again,  Is there a way to just have it try a rescan after error?  Or possibly have the program restart itself?

**Comment by ipsingh06** [comment]
Yes I'm aware of the issue. The next release will retry the remote scan when this specific error occurs rather than stop scanning altogether.

**Comment by ipsingh06** [comment]
This is fixed in the v0.3
