### ISSUE TITLE
Ability to change port

### ISSUE THREAD

**Issue by M1kep** [ipsingh06/seedsync#23]
Hi there, I'm wondering if there is anything that would restrict me from setting the port to a new value? It seems every-time that I edit the file the system errors our with the incomplete config error.

I may just be missing something so I'll have to take another look tomorrow. Worst case, this can turn into a request to be able to update that value.

**Comment by ipsingh06** [comment]
I cannot think of any reason why that would happen.

If you are using the docker version, you don't have to change the port setting at all, you can simply update the parameter '-p <new port>:8800'

**Comment by M1kep** [comment]
I can't seem to see why it's failing, as the app is compiled I'm having a hard time throwing log lines into it for test. I've attempted to setup the dev environment on my Mac, but that's been rough and even after getting pip to install dependencies with Python 3.5 and pycharm connecting it now wont make....

Would you be able to test a config similar to the below?

[General]
debug = True

[Lftp]
remote_address = 155.62.54.34
remote_port = 35003
remote_username = randomusername
remote_path = Sync/
local_path = /media/BBB/SyncFolder
remote_path_to_scan_script = /tmp/scanfs
num_max_parallel_downloads = 2
num_max_parallel_files_per_download = 4
num_max_connections_per_root_file = 4
num_max_connections_per_dir_file = 4
num_max_total_connections = 16

[Controller]
interval_ms_remote_scan = 30000
interval_ms_local_scan = 10000
interval_ms_downloading_scan = 1000

[Web]
port = 8800

I think this section is returning true for some reason but can't figure out why exactly:

https://github.com/ipsingh06/seedsync/blob/db7c49d8f84733a07b61a723c1e41a154d4427d6/src/python/seedsync.py#L319-L325

**Comment by M1kep** [comment]
Additionally, it looks like a lot of settings from https://github.com/ipsingh06/seedsync/blob/db7c49d8f84733a07b61a723c1e41a154d4427d6/src/angular/src/app/pages/settings/options-list.ts aren't displayed on the settings page. I may be just not understanding the Angular, but if the settings in that file were present that'd make the config file modifications much easier
