### ISSUE TITLE
Error with latest image: "An error occurred while installing scanner script to remote server."

### ISSUE THREAD

**Issue by flatlinebb** [ipsingh06/seedsync#24]
Getting error today after updating to the latest image:

[https://gist.github.com/flatlinebb/97a93ac788858533b608a06541ed48e3](url)

The most relevant section appears to be this:
`File "/app/python/ssh/sshcp.py", line 97, in __run_command
    raise SshcpError("Bad hostname: {}".format(self.__host))
ssh.sshcp.SshcpError: Bad hostname: 176.9.148.85
`
I do not recognize this IP, it is not my docker network, or LAN.

**Comment by ipsingh06** [comment]
What does your config look like?

**Comment by flatlinebb** [comment]
I apologize, I made a small mistake. I do know that IP address - that's the server I'm connecting to. (I'm more used to using the domain name). So yes, 176.9.148.85 is the correct host IP, it is live and pingable from my docker VM.

Are you asking for the docker command I use to launch the container, or the actual settings.cfg file for seedsync?

Here is the docker command I use:
`docker run -d --name=seedsync --hostname $HOSTNAME -p 8800:8800 -v /media/usb2/sabnzb/downloads/complete:/downloads -v /home/bart/docker_configs/seedsync:/config -v /home/bart/.ssh:/root/.ssh ipsingh06/seedsync`


And the settings.cfg, with some stuff redacted:
`[General]
debug = False
verbose = False

[Lftp]
remote_address = 176.9.148.85
remote_username = bart
remote_password = xxxxxxxxxxxx
remote_port = 22
remote_path = /home/bart/rtdata
local_path = /downloads
remote_path_to_scan_script = /home/bart/scanfs
use_ssh_key = True
num_max_parallel_downloads = 10
num_max_parallel_files_per_download = 5
num_max_connections_per_root_file = 10
num_max_connections_per_dir_file = 10
num_max_total_connections = 100
use_temp_file = True

[Controller]
interval_ms_remote_scan = 30000
interval_ms_local_scan = 10000
interval_ms_downloading_scan = 1000
extract_path = /tmp
use_local_path_as_extract_path = True

[Web]
port = 8800

[AutoQueue]
enabled = False
patterns_only = False
auto_extract = True
`

**Comment by ipsingh06** [comment]
The new image no longer runs the app as the root user. Try changing the /root/.ssh path to /home/user/.ssh

**Comment by flatlinebb** [comment]
Do I literally use the path "/home/user/.ssh", or do I change it to my username "bart"?

I'm getting this now:
` docker run -it --name=seedsync5 --hostname $HOSTNAME -p 8800:8800 --user 1000:1000 -v /media/usb2/sabnzb/downloads/complete:/downloads -v /home/bart/docker_configs/seedsync:/config -v /home/bart/.ssh:/home/bart/.ssh ipsingh06/seedsync
Traceback (most recent call last):
  File "/app/python/seedsync.py", line 376, in <module>
    seedsync = Seedsync()
  File "/app/python/seedsync.py", line 59, in __init__
    config.to_file(self.config_path)
  File "/app/python/common/persist.py", line 53, in to_file
    with open(file_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/config/settings.cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/python/seedsync.py", line 384, in <module>
    Seedsync.logger.exception("Caught exception")
AttributeError: 'NoneType' object has no attribute 'exception'
`

I think that the /config/settings.cfg file may still have root permissions inside the container?

**Comment by ipsingh06** [comment]
Try this command

docker run -it --name=seedsync5 --hostname $HOSTNAME -p 8800:8800 -v /media/usb2/sabnzb/downloads/complete:/downloads -v /home/bart/docker_configs/seedsync:/config -v /home/bart/.ssh:/home/user/.ssh ipsingh06/seedsync

**Comment by flatlinebb** [comment]
OK, the path for the config folder was wrong - it should be "/home/bart/docker/seedsync:/config", so that got us past the permission error on the settings.cfg file.

However, it's still crashing with this error:

`2019-02-01 21:41:18,698 - INFO - RemoteScanner.RemoteScanner (RemoteScanner/RemoteScanner) - Installing local:/app/scanfs to remote:/home/bart/scanfs
Process RemoteScanner:
Traceback (most recent call last):
  File "/app/python/controller/scan/remote_scanner.py", line 115, in _install_scanfs
    remote_path=self.__remote_path_to_scan_script)
  File "/app/python/ssh/sshcp.py", line 169, in copy
    args=" ".join(args)
  File "/app/python/ssh/sshcp.py", line 97, in __run_command
    raise SshcpError("Bad hostname: {}".format(self.__host))
ssh.sshcp.SshcpError: Bad hostname: 176.9.148.85
`

**Comment by flatlinebb** [comment]
Sorry, accidentally closed.

**Comment by flatlinebb** [comment]
OK, making progress. The username that the container runs under is seedsync, so this needs to be this:
`-v /home/bart/.ssh:/home/seedsync/.ssh`

Then it works. Figured it out by doing a console session inside the container, and looked at who owned the /config folder. Had to remove the the CMD in Portainer first, so it wouldn't try to execute on start.
The issue that makes it so hard to diagnose these issues is the error message coming from the container - it's useless. "Bad hostname" can mean a lot of things. In this case, it meant "I can't find the ssh key so I can't connect". I realize that I created this problem by mapping my .ssh folder inside the container, instead of creating new keys.

Any way to make the error messages a little more useful?

And here is my full docker command for those that want to map the ssh folder correctly, and maybe stumble on this through a Google search in a few years:

```
docker run -d --name=seedsync \
  --hostname $HOSTNAME \
  -p 8800:8800 \
  --user 1000:1000 \
  -v <downloads folder on host>:/downloads \
  -v <config folder on host>:/config \
  -v <.ssh folder on host>:/home/seedsync/.ssh \
  ipsingh06/seedsync

```
The user ID is the same as the user on my host, which I  got by running the id command:
```
id
uid=1000(bart) gid=1000(bart) 
```
By using the same id, the files should have correct permissions.

**Comment by ipsingh06** [comment]
Glad to hear it's working now. I'll look at improving the error message in the future.

**Comment by flatlinebb** [comment]
Now I'm actually trying to download a file and I'm getting permission denied errors :(

```
 2019/02/01 17:00:04 - INFO - RemoteScanner.RemoteScanner - Skipping remote scanfs installation: already installed

2019/02/01 17:00:33 - INFO - seedsync.Controller - Received command Action.QUEUE for file xxxxxxxxx.s02e06.1080p.web.x264-tbs.mkv

2019/02/01 17:00:34 - WARNING - ActiveScanner.ActiveScanner - Path does not exist: /downloads/xxxxxxxxxxx.s02e06.1080p.web.x264-tbs.mkv

2019/02/01 17:00:35 - WARNING - ActiveScanner.ActiveScanner - Path does not exist: /downloads/xxxxxxxxxxxxxxxxx.s02e06.1080p.web.x264-tbs.mkv

2019/02/01 17:00:36 - WARNING - ActiveScanner.ActiveScanner - Path does not exist: /downloads/xxxxxxxxxxxxxxxx.s02e06.1080p.web.x264-tbs.mkv

2019/02/01 17:00:36 - ERROR - seedsync.Controller.Lftp.LftpJobStatusParser - LftpJobStateParser error: Unrecognized line 'pget: /home/bart/rtdata/xxxxxxxxxxx.s02e06.1080p.web.x264-tbs.mkv: /downloads/xxxxxxxxxxxxxxx.s02e06.1080p.web.x264-tbs.mkv: Permission denied'

2019/02/01 17:00:36 - ERROR - seedsync.Controller.Lftp.LftpJobStatusParser - Status: pget: /home/bart/rtdata/xxxxxxxxxxxxx.s02e06.1080p.web.x264-tbs.mkv: /downloads/xxxxxxxxxxxxxxxx.s02e06.1080p.web.x264-tbs.mkv: Permission denied 
```

I'm running with the --user switch. And I also tried adding these two switches:
```
-e PGID=1000
-e PUID=1000
```

Same permission error.

**Comment by flatlinebb** [comment]
Changing the ownership of the /downloads folder from root to seedsync worked. The file is downloading now. Maybe modify the image and the owner of the /downloads folder to whatever user is specified when launching the container, if --user is used? Or just hard-code it to be owned by the seedsync user since that user is automatically created in the image?

This is the command I used as root in the container console, for other people's reference:
```
chown -Rv seedsync:seedsync /downloads
```

```
-R makes it recursive inside the folder
-v makes it verbose and tell you what it did
user:group defines the new owner
/folder-name is the folder you want to change the rights of
```

**Comment by ipsingh06** [comment]
Odd, the /downloads folder is already owned by seedsync when the image is compiled. If it wasn't for you then something must have gone wrong while running the image.

Also if you mount a host directory to /downloads, the permissions will carry over from the host directory.

I hope everything is working as is now.
