### ISSUE TITLE
Installing this as a docker in unraid

### ISSUE THREAD

**Issue by Nach0-Stallion** [ipsingh06/seedsync#25]
Hi, I have been trying to install this as a docker on my UNRAID server, I'm quite new to unraid but have installed a few dockers and plugins with without issues.
that appears to be happening is when installing, the options to set the downloads directory or config file directory are not shown, however someone posting screenshots of the previous version installing to unraid show all the required fields to be filled in.

![](https://i.redd.it/9mkaeaj7m3821.png)
This screenshot is a user on reddit having permission issue (that was resolved in the latest update) as you can see, the fields for config and sync are there and changeable, however on mine
<img width="1007" alt="screen shot 2019-02-03 at 2 44 56 pm" src="https://user-images.githubusercontent.com/47112682/52172782-541f8000-27c2-11e9-82a6-71f9bf150130.png">
there are no such options, so am I doing something wrong or has the user in the previous image done something differently to get those options?

I posted this on Reddit and the author requested I post here.
Cheers.

**Comment by ipsingh06** [comment]
Hi,

I am not familiar with that UI. Do you know what software Unraid uses to provide a configurable UI for running docker images?

**Comment by Nach0-Stallion** [comment]
Hi,
I am quite new to Unraid and the whole Docker system in general so I am unsure, I only discovered your app because someone posted an issue with file permissions in January but I believe they were running ver 6, and the screenshots they provide have all the needed parameters, but when I try to install with ver 7 I get none of those.
I tried installing manually and even got the webui running but it showed the service wasn’t running 

Regards,
Richard.

**Comment by Nach0-Stallion** [comment]
Hi,
During the web based install you get the option of setting up parameters, I tried adding them exactly as I saw with another user and again, can get the webui to load but no response from the app.
I even saw the config file, added my FTP details manually but get errors that I didn’t understand
I’m at work right now so don’t have logs to give you but will greatly appreciate any help you can offer :)

Regards,
Richard.

**Comment by Nach0-Stallion** [comment]
Hi,
I have managed to get the web UI working, but it says it’s waiting for the service and I can cycle through the menus but not manipulate any settings. 
I have gone into the logs and the logs say it’s not fully not configured. So I have edited the config and manually entered my FTP details etc but the GUI while loading, doesn’t respond and am then presented with more errors in the log

**Comment by flatlinebb** [comment]
See the 3 links at the bottom on the second, darker screenshot? They allow you to add more fields. You should be able to click the + and add a field for the config folder and possibly other docker parameters.

**Comment by Nach0-Stallion** [comment]
> See the 3 links at the bottom on the second, darker screenshot? They allow you to add more fields. You should be able to click the + and add a field for the config folder and possibly other docker parameters.

Hi,
Yeah I have tried using that to add the fields to match what is in the lighter screenshot.. I have at some point gotten the WebUI working, but it shows an error that the service isn't running or something similar.
the logs jus show the config is not complete, regardless of how much I change things..

**Comment by rednessreliever** [comment]
No issues running under Unraid for me. Here is my configuration:

* Downloads Path (Path)
  * Local: /mnt/user/Torrents/completed
  * Container: /downloads
* Config Path (Path)
  * Local: /mnt/user/appdata/seedsync
  * Container: /config
* Main Port (Port)
  * Host: 8800
  * Container: 8800
* Process User ID (Variable)
  * Key: PUID
  * Value: 99
* Process Group ID (Variable)
  * Key: PGID
  * Value: 100
* File Mode Creation Mask (Variable)
  * Key: UMASK
  * Value: 000

Honestly not sure if defining PUID/PGID is necessary with the most recent update, but make sure you do define the UMASK otherwise you'll have to manually change file permissions to move or rename downloaded files.

Depending on your seedbox configuration you might need to define your server paths with the FULL path, not just relative to wherever you drop in via FTP. Also, the server script path needs to end with /scanfs.

**Comment by d2dyno** [comment]
Running under unraid works perfectly fine for me as well.

**Comment by flippedcracker** [comment]
I just tried to install this on my 6.7.0 unraid server and the install seemed to complete, but when the container starts, the log just says 

> 2019-03-27 17:27:35,403 - INFO - seedsync (MainProcess/MainThread) - Debug mode is disabled.
2019-03-27 17:27:35,406 - INFO - seedsync (MainProcess/MainThread) - Starting seedsync
2019-03-27 17:27:35,952 - INFO - seedsync.WebApp (MainProcess/MainThread) - Html path set to: /app/html
2019-03-27 17:27:35,964 - ERROR - seedsync (MainProcess/MainThread) - Config is incomplete

And then stops. And the config directory only has 3 files in it. autoqueue.persist, controller.persist, and settings.cfg.

Anyone know what I'm missing? thanks.

**Comment by rednessreliever** [comment]
Sounds like there is something wrong with your configuration. Post the contents of settings.cfg (after removing any personal information).

**Comment by flippedcracker** [comment]
> Sounds like there is something wrong with your configuration. Post the contents of settings.cfg (after removing any personal information).
> 
> Also please note that Unraid 6.7 is not a stable release so there could be something funky going on outside this application.

Well, I feel kinda dumb. You asking about settings.cfg made me actually look at that file and saw that I had to change some stuff in there. I changed it and now it works. Thanks!

**Comment by derpingit** [comment]
is this no longer available via unraid apps? i can't find it :/

**Comment by rednessreliever** [comment]
> is this no longer available via unraid apps? i can't find it :/

I'm not sure it ever was. Follow my post above for setting up your own template: https://github.com/ipsingh06/seedsync/issues/25#issuecomment-466546009

**Comment by AlwaysThinkofAvery** [comment]
Thanks for the info on setting this up in Unraid.  I got it working but have a question.  It's reasonable to assume that the connection is using SFTP, correct?  There is no indication from the WebUI that it is encrypting any transfers.

**Comment by derpingit** [comment]
> Hi, I have been trying to install this as a docker on my UNRAID server, I'm quite new to unraid but have installed a few dockers and plugins with without issues.
> that appears to be happening is when installing, the options to set the downloads directory or config file directory are not shown, however someone posting screenshots of the previous version installing to unraid show all the required fields to be filled in.
> 
> ![](https://camo.githubusercontent.com/307a83a96fa3b6670a1839c784cd77c7937bd9dc/68747470733a2f2f692e726564642e69742f396d6b6165616a376d333832312e706e67)
> This screenshot is a user on reddit having permission issue (that was resolved in the latest update) as you can see, the fields for config and sync are there and changeable, however on mine
> <img alt="screen shot 2019-02-03 at 2 44 56 pm" width="1007" src="https://user-images.githubusercontent.com/47112682/52172782-541f8000-27c2-11e9-82a6-71f9bf150130.png">
> there are no such options, so am I doing something wrong or has the user in the previous image done something differently to get those options?
> 
> I posted this on Reddit and the author requested I post here.
> Cheers.

I didn’t get a chance to thank you for your instructions . They worked out great . I managed to set it up as a docker run prior to your comment, but I didn’t know you could create templates that would rebuild on shutdown. The only thing I had to do in addition to following your instructions was to exec into the docker and setup the no password ssh session with my server . This worked out great, and it is by far the fastest way I’ve found to get stuff from my box
