### ISSUE TITLE
Need a way to stop/pause/delete from queue multiple downloads

### ISSUE THREAD

**Issue by diablc** [ipsingh06/seedsync#26]
I had to reinstall Seedsync due to an issue.  Now I have to stop each file (100+) from re-downloading.  To say the least this is a pain.

**Comment by ipsingh06** [comment]
Try disabling Auto Queue in settings and restarting.

**Comment by diablc** [comment]
disabling Auto Queue solves the issue, but now I have to manually queue all the downloads which defeats the purpose.

**Comment by diablc** [comment]
Force instance, I have 2 items that have completely downloaded, but continue to re-download every time I restart the app (due to app not being able to communicate with the server).  They show in a paused state, the only way to prevent this is to move the file location on my server so it thinks the files have been deleted.
