### ISSUE TITLE
An error occurred while scanning the remote server

### ISSUE THREAD

**Issue by ProphetSe7en** [ipsingh06/seedsync#28]
Error after error. Have noe clue on whats wrong.

LOG: https://pastebin.com/qY8qzJNj

Settings: https://pastebin.com/zxrtRnr1

**Comment by rednessreliever** [comment]
I had this happen too, and ended up setting the server script path closer to my server directory, e.g. `/deluge/scanfs/` and `/deluge/completed` which fixed it.

**Comment by PieButNotThatPie** [comment]
My path is as short as :
`/files/completed`
`/files/scanfs`

But I still got the same error

`ERROR - RemoteScanner.RemoteScanner - Caught an SshError
Traceback (most recent call last):
File "/app/python/controller/scan/remote_scanner.py", line 66, in scan
self.__remote_path_to_scan)
File "/app/python/ssh/sshcp.py", line 143, in shell
args=" ".join(args)
File "/app/python/ssh/sshcp.py", line 109, in __run_command
raise SshcpError(sp.before.decode())
ssh.sshcp.SshcpError: 
exec request failed on channel 0
`
