### ISSUE TITLE
Extracting

### ISSUE THREAD

**Issue by amaru007** [ipsingh06/seedsync#29]
Can't seem to extract to the directory I want.
Finally managed to get this installed properly and it works great.
In the setup I used the download dir:  -v /home/user/downloads:/downloads \
all downloaded files go to /downloads
I wish to extract to folder  /home/user/plex/tv  but nothing shows up there after extracting
files extract fine if I choose the option: Extract archives in the downloads directory
How can I fix this?

**Comment by rednessreliever** [comment]
I don't use the extraction feature myself, but it seems like you might need to define another path:

`-v /home/user/plex/tv:/tmp`

**Comment by ipsingh06** [comment]
The suggestion solution is correct. Please re-create this issue if you're still having problems.
