### ISSUE TITLE
Installing SeedSync under Docker running on a Synology NAS

### ISSUE THREAD

**Issue by sarquiss** [ipsingh06/seedsync#34]
Attempting to run SeedSync under Docker on my Synology 1817+ NAS. However, the container unexpectedly terminates as soon as it starts up.

The errors in the log indicate a permissions issue:

**_PermissionError: [Errno 13] Permission denied: '/config/settings.cfg'_** 

I have configured the settings as such:

**- Downloads Path (Path)** 
- **Local:** /applications/torrents/downloads
- **Container:** /downloads
**- Config Path (Path)** 
- **Local:** /applications/configs/seedsync
- **Container:** /config
**- Main Port (Port)** 
- **Host:** 40000
- **Container:** 8800
**- Process User ID (Variable)** 
- **Key:** PUID
- **Value:** 1026
**- Process Group ID (Variable)** 
- **Key:** PGID
- **Value:** 101

If I do not configure the config path everything works until I change a setting and then I receive an error regarding permissions to the Download path.

All my other containers are running with the same PUID and PGID context. Any thoughts?

**Comment by sarquiss** [comment]
I was able to resolve the permissions issue by creating the container via CLI. However, I am receiving the following error after setting up the configuration:


_2019-03-14 23:46:03 | stderr | 2: re.compile("b'Could not resolve hostname'")
-- | -- | --
2019-03-14 23:46:03 | stderr | 1: re.compile("b'lost connection'")
2019-03-14 23:46:03 | stderr | 0: re.compile("b'password: '")_

I do also notice the following error in the logs:

_before (last 100 chars): b'No user exists for uid 1026\r\r\n'_

**Comment by ipsingh06** [comment]
Please try the latest version (v0.7.1). I updated the Docker image to (hopefully) address this issue.
