### ISSUE TITLE
[request]  Auto retry when server disconnects.

### ISSUE THREAD

**Issue by diablc** [ipsingh06/seedsync#35]
When the Seedsync gets a non-response from the server, It shows an error, but it never tries to reconnect.  I have to restart the docker every time.  My host apparently doesn't have 24/7 uptime, because it will randomly disconnect, and if I don't open the app and see that seedsync is disconnected, i won't know.

**Comment by markcarver** [comment]
This happens all the time, not entirely sure why (also likely remote network timeouts/issues, runs as a daemon via docker on my Synology NAS).

All I have to do to fix this is literally click the "Restart" menu item in the sidebar... but I have to do this manually several times a day. This creates a bottleneck on my user interaction and essentially halts all importing into the server thus breaking the entire automation workflow.

IMO, this is a critical bug. It shouldn't simply "stop" when it encounters an issue like this, it should retry ever 5 mins or so, maybe a max of 10 times (this should be configurable).

**Comment by markcarver** [comment]
@ipsingh06 this is starting to get really annoying...

**Comment by markcarver** [comment]
@ipsingh06 Any chance you could knock this one out soon? It still happens quite a lot.

**Comment by ipsingh06** [comment]
I'm taking a look at it. I hate it too.

**Comment by ipsingh06** [comment]
This has been added in v0.8.0.
