### ISSUE TITLE
An error occurred while scanning the remote server

### ISSUE THREAD

**Issue by danmed** [ipsingh06/seedsync#4]
So, i've got this set up now against my Ultraseedbox slot.. eventually figured out I had to set up ssh keys...

However i'm getting an "An error occurred while scanning the remote server"

https://pastebin.com/t2RBbMUh

This is my settings page

https://imgur.com/a/vC0AY

**Comment by ipsingh06** [comment]
In Server Script Path append an executable name, e.g. /home9/danmed/scanfs
