### ISSUE TITLE
Unpickling error

### ISSUE THREAD

**Issue by Dulanic** [ipsingh06/seedsync#45]
So I am trying this program for the first time, but I am running into a problem. It seems to load the scanner to the seedbox as expexted, but then gets some Unpickling error.

Any assistance would be appreciated! Thanks!

http://paste.ubuntu.com/p/6DYd36Y2cT/

**Comment by ipsingh06** [comment]
It looks this this is introduced by an error in your .bashrc on the remote server. Try fixing or temporarily removing your .bashrc on the remote server.
