### ISSUE TITLE
Any chance of connecting through SOCKS5 proxy?

### ISSUE THREAD

**Issue by sinbrkatetete** [ipsingh06/seedsync#49]
Is there a chance you could / want to add this feature? I have a need to sometimes connect to servers that belong to people I don't like/trust and I usually use a tor socks proxy for such things. I'm tired of using Filezilla and am looking for something I can automate using my minuscule knowledge of all things sftp / docker n/unraid etc. 

Thanks in advance

**Comment by ipsingh06** [comment]
Sorry I have no plans right now support connection through a SOCKS proxy as lftp [doesn't](https://github.com/lavv17/lftp/issues/510) include it by default.
