### ISSUE TITLE
libreadline6 Not Available on Debian 9

### ISSUE THREAD

**Issue by Smoz** [ipsingh06/seedsync#5]
I can't get this installed on Debian 9.3. Apparently 'libreadline6' isn't available so I tried using 'libreadline-dev' but still doesn't work.

I found [this](https://github.com/haconiwa/haconiwa/issues/120) when researching the issue and it appears that packages built on ubuntu use readline6 which isn't available on Debian 9. Any chance we can get a dockerfile for this or another workaround?

edit
It also says that it can't install libssl. I haven't researched this one though.

![image](https://user-images.githubusercontent.com/25465045/37115026-9c3e9ba0-220f-11e8-9fbd-0f529cb47dd1.png)

**Comment by ipsingh06** [comment]
I've released a docker image. See the README for installation instructions.
Please create a new issue if you experience problems with that.

**Comment by iamoumuamua** [comment]
I have the same problem in Xubuntu 18.10 Cosmic Cuttlefish. 'Dependency problems' prevent just installing the .deb file and I can't resolve the dependencies. I have libreadline7 but not 6. I can't find any README file. There are some install scripts I guess. I am not clear on what they do exactly though. So a docker image is sort of like an iso file?
