### ISSUE TITLE
Changed .ssh folder location

### ISSUE THREAD

**Issue by flatlinebb** [ipsingh06/seedsync#52]
Looks like the location of the .ssh folder has been changed in the latest docker version. Instead of using the /home/seedsync/.ssh folder, it now looks for ssh keys in /tmp/user/.ssh.
Since I was mapping my ssh keys from my docker host to the container, my connection stopped working, until I remapped to the /tmp directory.
Any reason for the change?
Also, the documentation might need to be updated, since the root user is not used anymore, and the part about installing keys is now incorrect.

**Comment by ipsingh06** [comment]
This was an oversight on my part. I've fixed this in the newest release, you should go back to using `/home/seedsync/.ssh`. Thanks for the pointing this out!
I've also updated the documentation as well.
