### ISSUE TITLE
Could this help with permissions problems?

### ISSUE THREAD

**Issue by quadcom** [ipsingh06/seedsync#53]
Found an article on Synology's forums talking about the issue many have faced. Users assigned permissions to files modified by Seedsync.

> "I was able to solve my problem by executing chown command after the file-copy operation. I'm not sure that I understand this completely, but the only difficulty with that approach is that docker-container references users by UID, while DSM references them by name. In other words, this does it for me:
> 
> via telnet (and, I'm assuming, SSH):
> chown myuser file-path
> 
> from within docker-container:
> chown 2020 file-path
> 
> So, "2020" is UID for user "myuser". And, to find out the UID for a user (since that's not displayed anywhere within DMS, that I can see), execute this within telnet connection/client:
> id -u myuser
> This prints
> 2020"

https://community.synology.com/enu/forum/17/post/110870

**Comment by quadcom** [comment]
Perhaps providing the username or UID of the user on the host system, as we did before. The CHOWN command can use that and correct the owner of the files on the host.

**Comment by quadcom** [comment]
I've noticed (on my Synology) that the default group (1000) is also assigned to files added by SS.

**Comment by quadcom** [comment]
My apologies if you are already aware of this. I'm trying to help out in the only way I know how.

There was a comment in the thread on the Synology board that read to me to be a simple explanation of getting user permissions working with host systems.

Hopefully this might be something that leads you to the answer.

> easy solution:
> If you need the container to access a mounted volume with a specific uid:gid, you need to add a group with the desired gid and a user with the desired uid.
> You need to add something like 'groupadd' and 'useradd' to add both in your dockerfile. When you build the image, the uid:gid is backed into the image.
> 
> proper solution:
> If you want to pass in the uid and gid as a parameter to dynamicly configure them during container start, you need to have an entrypoint script that does at least modify the gid of an existing group and the uid on an existing user. I would strongly advice to take a look at s6-overlay, it makes environment variable handling quite easy, takes care of the pid1 problem and more.
> 
> A good starting point is https://github.com/linuxserver/docker-baseimage-xenial .
> 
> You might even think about using linuxserver/docker-baseimage-xenial as your base image, and just add your "service" like they do in https://github.com/linuxserver/docker-plex (the magic happens in the /root folder of the project repo).

**Comment by quadcom** [comment]
Sorry about all the messages here.

Is there a simple way to update to the new version? Maybe from a terminal window like apt get update?

The last update had me download the new Dockerhub image and reconfig the container. Took a while to get things going smoothly again.

Thanks for all your hard work on this. I wish I had more skill in coding to be of some assistance.

**Comment by ipsingh06** [comment]
Hi @quadcom 
I expect the file permission issues to be fixed in the newest version (v0.7.3). You have to pass in the correct user and group ids when calling docker run using the '--user <uid>:<gid>' option. Please let me know of any errors that show up with Synology.

Running with the latest docker image should be very easy. You just have to run:
```bash
docker pull ipsingh06/seedsync:latest
```
and re-run the docker run command.

**Comment by My-userid** [comment]
Would it be possible to set the user uid:gid with environment variables ?

**Comment by quadcom** [comment]
Hey Inder,

so 0.7.3 is still doing the same thing. I have debug logs for you. Where can I send them (privately)?

**Comment by ipsingh06** [comment]
@My-userid The uid and gid need to be passed to the `docker run` command using the `--user` option. I'm not aware of any way to pass that using environment variables.

@quadcom I took a look at the logs. I'm not familiar with Synology, but specifying an environment variable "user" won't do anything. This is an option that needs to be passed to the `docker run` command. Sorry I don't know enough about Synology to tell you how to do that.

**Comment by ipsingh06** [comment]
This user [here](https://github.com/ipsingh06/seedsync/issues/34) ran Synology with a non-default user, I assume you would need to do the same.

**Comment by quadcom** [comment]
OK, the 'user' option has fixed it. The frustrating part is Synology's implementation of Docker. The ONLY opportunity there is to define run options is when the container is being built form the image page.

But, that still didn't work in this case. I had to run the docker run command fro man SSH window. Once I did that, the container was built and started up. 

Here is the run command for others running a Synology Docker setup. Ensure everything is one line with spaces in between the content of each line.

> sudo docker run 
> --name SeedSync **[This is what you want to call the container]**
> -p 8802:8800 **[this is the port settings. {container side}:{host side}]**
> -v {path on NAS}:/config **[The path on the NAS where config files are stored]**
> -v {path on NAS}:/incoming **[The path on the NAS where the DL'd files are stored]**
> --user {UID}:{GID} **[The user ID and group ID on the NAS that files DL'd are owned by]**
> ipsingh06/seedsync:latest **[This is the name of the image stored in the image tab of the Docker UI]** 

Hope this helps other get up and running.

**Comment by My-userid** [comment]
> @My-userid The uid and gid need to be passed to the `docker run` command using the `--user` option. I'm not aware of any way to pass that using environment variables.
> 
Look at many of Linuxserver.io dockers.. They use variables for the user option.
IE: https://hub.docker.com/r/linuxserver/sonarr/

Problem is, with Synology it is not as easy to apply commandline options as the GUI does not support it.

**Comment by ipsingh06** [comment]
Thanks for the link @My-userid . Looks like Linuxserver.io dockers implement all of these containers on top of the s6 process supervisor and then use `s6-setuidgid` to run the app as that user and group. This is a massive change for the Seedsync docker image. I will leave this this ticket open for now.

**Comment by quadcom** [comment]
> > @My-userid The uid and gid need to be passed to the `docker run` command using the `--user` option. I'm not aware of any way to pass that using environment variables.
> 
> Look at many of Linuxserver.io dockers.. They use variables for the user option.
> IE: https://hub.docker.com/r/linuxserver/sonarr/
> 
> Problem is, with Synology it is not as easy to apply commandline options as the GUI does not support it.

I've resorted to spinning up a container using the SSH login for my Synology. I've got it down to a simple process. I'll put this down to the less than optimized Docker support in Synology NAS devices.

When I have a moment I can put together a step-by-step doc on spinning up a SS docker container on a Synology box.

**Comment by ipsingh06** [comment]
@quadcom that would be great! I can include your guide in the official documentation.

**Comment by encg** [comment]
> OK, the 'user' option has fixed it. The frustrating part is Synology's implementation of Docker. The ONLY opportunity there is to define run options is when the container is being built form the image page.
> 
> But, that still didn't work in this case. I had to run the docker run command from an SSH window. Once I did that, the container was built and started up.
> 
> Here is the run command for others running a Synology Docker setup. **_Ensure everything is one line with spaces in between the content of each line._**
> 
> > sudo docker run
> > --name SeedSync **[This is what you want to call the container]**
> > -p 8802:8800 **[this is the port settings. {container side}:{host side}]**
> > -v {path on NAS}:/config **[The path on the NAS where config files are stored]**
> > -v {path on NAS}:/incoming **[The path on the NAS where the DL'd files are stored]**
> > --user {UID}:{GID} **[The user ID and group ID on the NAS that files DL'd are owned by]**
> > ipsingh06/seedsync:latest **[This is the name of the image stored in the image tab of the Docker UI]**
> 
> I hope this helps others get up and running.

This is perfect - thanks. I did `id $user` to get my UID & GID for anyone else that's trying to figure that out.
