### ISSUE TITLE
Waiting for SeedSync service to respond... after install

### ISSUE THREAD

**Issue by OlivierFerriot** [ipsingh06/seedsync#56]
After installing seedsync in a docker on unraid, I get this message "Waiting for SeedSync service to respond..." when I connect to the WebGUI at the top. I can only change tabs but nothing else is clickable. Can't restart, the options are empty andd can't be changed nothing...

The log on unraid don't say much :
03 01:58:04,133 - INFO - web_access (MainProcess/worker 1) - 192.168.1.100 - - [03/Jun/2020:01:58:04 +0000] "GET /assets/logo.png HTTP/1.1" 200 6872 "http://192.168.1.10:8800/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
2020-06-03 01:58:30,762 - INFO - seedsync (MainProcess/MainThread) - Caught signal SIGTERM
2020-06-03 01:58:30,762 - INFO - seedsync (MainProcess/MainThread) - Exiting Seedsync
2020-06-03 11:48:36,566 - INFO - seedsync (MainProcess/MainThread) - Debug mode is disabled.
2020-06-03 11:48:36,569 - INFO - seedsync (MainProcess/MainThread) - Starting seedsync
2020-06-03 11:48:37,479 - INFO - seedsync.WebApp (MainProcess/MainThread) - Html path set to: /app/html
2020-06-03 11:48:37,486 - ERROR - seedsync (MainProcess/MainThread) - Config is incomplete

**Comment by ipsingh06** [comment]
Which method of install are you using, docker or debian package?

**Comment by OlivierFerriot** [comment]
Docker on unraid.
I mapped the /config and /download folders and used the --user uid:pid additional parameter.

**Comment by ipsingh06** [comment]
Which browser are you using? Can you try a different browser?

**Comment by OlivierFerriot** [comment]
I'm using Firefox. Tried Chrome and it worked (?) filled the settings tabs that was almost empty. Restarted as it asked me an now I have the `An error occurred while installing scanner script to remote server.` message.

Here is my log :
`2020/06/06 02:20:38 - INFO - seedsync.ServerActionHandler - Received a restart action
2020/06/06 02:20:38 - INFO - seedsync - Exiting Seedsync
2020/06/06 02:21:11 - ERROR - RemoteScanner.RemoteScanner.Sshcp - Timed out Traceback (most recent call last): File "/app/python/ssh/sshcp.py", line 79, in __run_command 'Could not resolve hostname', # i=2, bad hostname File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 344, in expect timeout, searchwindowsize, async_) File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 372, in expect_list return exp.expect_loop(timeout) File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 181, in expect_loop return self.timeout(e) File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 144, in timeout raise exc pexpect.exceptions.TIMEOUT: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x1551574afdd0> command: /usr/local/sbin/ssh args: ['/usr/local/sbin/ssh', '-p', '22', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=error', '-o', 'PubkeyAuthentication=no', 'goodiesa@ftp.goodies.appboxes.co', "echo 'b9133371fa4ba822bd6ec3a69ab6f0b1 /tmp/scanfs' | md5sum -c --quiet"] buffer (last 100 chars): b'mkdir: cannot create directory \xe2\x80\x98/home/seedsync\xe2\x80\x99: Permission denied\r\n' before (last 100 chars): b'mkdir: cannot create directory \xe2\x80\x98/home/seedsync\xe2\x80\x99: Permission denied\r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 43 child_fd: 60 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile(b'password: ') 1: re.compile(b'lost connection') 2: re.compile(b'Could not resolve hostname')
2020/06/06 02:21:11 - ERROR - RemoteScanner.RemoteScanner.Sshcp - Command output before: b'mkdir: cannot create directory \xe2\x80\x98/home/seedsync\xe2\x80\x99: Permission denied\r\n'
2020/06/06 02:21:11 - INFO - RemoteScanner.RemoteScanner - Installing local:/app/scanfs to remote:/tmp/scanfs
2020/06/06 02:21:41 - ERROR - RemoteScanner.RemoteScanner.Sshcp - Timed out Traceback (most recent call last): File "/app/python/ssh/sshcp.py", line 79, in __run_command 'Could not resolve hostname', # i=2, bad hostname File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 344, in expect timeout, searchwindowsize, async_) File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 372, in expect_list return exp.expect_loop(timeout) File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 181, in expect_loop return self.timeout(e) File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 144, in timeout raise exc pexpect.exceptions.TIMEOUT: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x1551574bc5d0> command: /usr/local/sbin/scp args: ['/usr/local/sbin/scp', '-q', '-P', '22', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=error', '-o', 'PubkeyAuthentication=no', '/app/scanfs', 'goodiesa@ftp.goodies.appboxes.co:/tmp/scanfs'] buffer (last 100 chars): b'mkdir: cannot create directory \xe2\x80\x98/home/seedsync\xe2\x80\x99: Permission denied\r\n' before (last 100 chars): b'mkdir: cannot create directory \xe2\x80\x98/home/seedsync\xe2\x80\x99: Permission denied\r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 50 child_fd: 61 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile(b'password: ') 1: re.compile(b'lost connection') 2: re.compile(b'Could not resolve hostname')
2020/06/06 02:21:41 - ERROR - RemoteScanner.RemoteScanner.Sshcp - Command output before: b'mkdir: cannot create directory \xe2\x80\x98/home/seedsync\xe2\x80\x99: Permission denied\r\n'
2020/06/06 02:21:41 - ERROR - RemoteScanner.RemoteScanner - Caught scp exception Traceback (most recent call last): File "/app/python/ssh/sshcp.py", line 79, in __run_command 'Could not resolve hostname', # i=2, bad hostname File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 344, in expect timeout, searchwindowsize, async_) File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 372, in expect_list return exp.expect_loop(timeout) File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 181, in expect_loop return self.timeout(e) File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 144, in timeout raise exc pexpect.exceptions.TIMEOUT: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x1551574bc5d0> command: /usr/local/sbin/scp args: ['/usr/local/sbin/scp', '-q', '-P', '22', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=error', '-o', 'PubkeyAuthentication=no', '/app/scanfs', 'goodiesa@ftp.goodies.appboxes.co:/tmp/scanfs'] buffer (last 100 chars): b'mkdir: cannot create directory \xe2\x80\x98/home/seedsync\xe2\x80\x99: Permission denied\r\n' before (last 100 chars): b'mkdir: cannot create directory \xe2\x80\x98/home/seedsync\xe2\x80\x99: Permission denied\r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 50 child_fd: 61 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile(b'password: ') 1: re.compile(b'lost connection') 2: re.compile(b'Could not resolve hostname') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/app/python/controller/scan/remote_scanner.py", line 115, in _install_scanfs remote_path=self.__remote_path_to_scan_script) File "/app/python/ssh/sshcp.py", line 169, in copy args=" ".join(args) File "/app/python/ssh/sshcp.py", line 102, in __run_command raise SshcpError("Timed out") ssh.sshcp.SshcpError: Timed out
2020/06/06 02:21:42 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 524, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 71, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 57, in scan
self._install_scanfs()
File "/app/python/controller/scan/remote_scanner.py", line 118, in _install_scanfs
raise AppError(Localization.Error.REMOTE_SERVER_INSTALL)
common.error.AppError: An error occurred while installing scanner script to remote server.
2020/06/06 02:21:42 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "/app/python/seedsync.py", line 162, in run
controller_job.propagate_exception()
File "/app/python/common/job.py", line 77, in propagate_exception
raise exc_info[1].with_traceback(exc_info[2])
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 524, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 71, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 57, in scan
self._install_scanfs()
File "/app/python/controller/scan/remote_scanner.py", line 118, in _install_scanfs
raise AppError(Localization.Error.REMOTE_SERVER_INSTALL)
common.error.AppError: An error occurred while installing scanner script to remote server.`

**Comment by OlivierFerriot** [comment]
Any ideas ? :)

**Comment by ipsingh06** [comment]
Could you please paste your configuration from the Settings page. It looks like your `Server script path` is set to a path where you don't have write permission.

**Comment by OlivierFerriot** [comment]
Well I tried to start the docker again and now I simply can't access the GUI anymore. The docker is started, I have a few error in the docker log in unraid but I can't access the GU. No idea why.
Tried to delete the docker and the appdata folder and reinstall again and same, can't access the GUI...

**Comment by OlivierFerriot** [comment]
Ok, morron here, forgot to remap the GUI port so go it working again.
Now the Server script path I didn't change because I have no idea what I'm supposed to map it to.
Is it supposed to be mapped to my local server or the distant one ? in which folder ?

**Comment by ipsingh06** [comment]
Oliver please post your Settings so I can get a better look at what might be wrong. I have a feeling that the reason you're getting this error is because you are trying to use your SSH keys from the host, and you haven't mapped the host folder. If so, you need to add the following option to your docker run command `-v <path to .ssh directory>:/home/seedsync/.ssh`

**Comment by OlivierFerriot** [comment]
ok so these are my settings (docker + app) cause I didn't know which one you needed :)
Here is my docker :
https://ibb.co/vsNvkxR

and here is the app :
https://i.ibb.co/5j0R0j1/seedsync.png

Hope this helps

**Comment by ipsingh06** [comment]
Leave Local Directory as `/download` as that refers to the path inside the docker image.
Everything else looks fine.

**Comment by OlivierFerriot** [comment]
I indeed can't, I'm trying to check with my seedbox supplier how to do that.
I'll come back when they give me a reply and I can try again :)

**Comment by OlivierFerriot** [comment]
So I managed to get SSH access but now that I modified the connection settings, if get another error...
Sorry :)
```
ERROR - RemoteScanner.RemoteScanner - Unpickling error: invalid load key, '/'. b'/home/app/.bashrc: line 1: /generate_container_user: No such file or directory\n\x80\x03]q\x00(csystem.file\nSystemFile\nq\x01)\x81q\x02}q\x03(X\x11\x00\x00\x00_SystemFile__nameq\x04X\x05\x00\x00\x00.syncq\x05X\x11\x00\x00\x00_SystemFile__sizeq\x06.....

[goes on for EVER, like 7 000 000 char long Ever :)]

2020/06/12 01:34:31 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 79, in scan
recoverable=False
controller.scan.scanner_process.ScannerError: An error occurred while scanning the remote server: 'Invalid pickled data'.
2020/06/12 01:34:31 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "/app/python/seedsync.py", line 162, in run
controller_job.propagate_exception()
File "/app/python/common/job.py", line 77, in propagate_exception
raise exc_info[1].with_traceback(exc_info[2])
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 79, in scan
recoverable=False
controller.scan.scanner_process.ScannerError: An error occurred while scanning the remote server: 'Invalid pickled data'.
```

**Comment by ipsingh06** [comment]
Looks like there's a problem in your remote server's bashrc as the scan script is getting this output at the beginning:
`/home/app/.bashrc: line 1: /generate_container_user: No such file or directory`

Try ssh'ing into your remote server and fixing this error.

**Comment by s0b** [comment]
Im having a similar issue but seems like mine is related to the locale:

```
2020/07/31 18:54:47 - INFO - RemoteScanner.RemoteScanner - Installing local:/app/scanfs to remote:/mnt/xxx/scanfs

2020/07/31 18:55:01 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob Traceback (most recent call last):
  File "/app/python/common/job.py", line 44, in run
    self.execute()
  File "/app/python/controller/controller_job.py", line 29, in execute
    self.__controller.process()
  File "/app/python/controller/controller.py", line 199, in process
    self.__propagate_exceptions()
  File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
    self.__remote_scan_process.propagate_exception()
  File "/app/python/common/app_process.py", line 124, in propagate_exception
    raise exc.re_raise()
  File "/app/python/common/app_process.py", line 30, in re_raise
    raise self.ee.with_traceback(self.tb)
  File "/app/python/common/app_process.py", line 87, in run
    self.run_loop()
  File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
    files = self.__scanner.scan()
  File "/app/python/controller/scan/remote_scanner.py", line 79, in scan
    recoverable=False
controller.scan.scanner_process.ScannerError: An error occurred while scanning the remote server: 'Invalid pickled data'.

2020/07/31 18:55:01 - ERROR - RemoteScanner.RemoteScanner - Unpickling error: unpickling stack underflow b'bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)\n\x80\x03]q\x00csystem.file\nSystemFile\nq\x01)\x81q\x02}q\x03(X\x11\x00\x00\x00_SystemFile__nameq\x04X\x03\x00\x00\x00asdq\x05X\x11\x00\x00\x00_SystemFile__sizeq\x06K\x00X\x13\x00\x00\x00_SystemFile__is_dirq\x07\x89X\x1e\x00\x00\x00_SystemFile__timestamp_createdq\x08NX\x1f\x00\x00\x00_SystemFile__timestamp_modifiedq\tcdatetime\ndatetime\nq\nC\n\x07\xe4\x07\x1f\x10\x16\x12\x01\x94\xfbq\x0b\x85q\x0cRq\rX\x15\x00\x00\x00_SystemFile__childrenq\x0e]q\x0fuba.'

2020/07/31 18:55:01 - ERROR - seedsync - Caught exception Traceback (most recent call last):
  File "/app/python/seedsync.py", line 162, in run
    controller_job.propagate_exception()
  File "/app/python/common/job.py", line 77, in propagate_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/app/python/common/job.py", line 44, in run
    self.execute()
  File "/app/python/controller/controller_job.py", line 29, in execute
    self.__controller.process()
  File "/app/python/controller/controller.py", line 199, in process
    self.__propagate_exceptions()
  File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
    self.__remote_scan_process.propagate_exception()
  File "/app/python/common/app_process.py", line 124, in propagate_exception
    raise exc.re_raise()
  File "/app/python/common/app_process.py", line 30, in re_raise
    raise self.ee.with_traceback(self.tb)
  File "/app/python/common/app_process.py", line 87, in run
    self.run_loop()
  File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
    files = self.__scanner.scan()
  File "/app/python/controller/scan/remote_scanner.py", line 79, in scan
    recoverable=False
controller.scan.scanner_process.ScannerError: An error occurred while scanning the remote server: 'Invalid pickled data'.

2020/07/31 18:55:03 - INFO - seedsync.Controller - Exited controller
```

I dont have sudo permissions to change the locale in the remote server. Is there any way to change the locale in the SeedSync docker image?

**Comment by ipsingh06** [comment]
Closing this for now - please try the latest version and create a new ticket if the problem still occurs.
