### ISSUE TITLE
Raspberry pi / arm support

### ISSUE THREAD

**Issue by L4yer** [ipsingh06/seedsync#57]
Hello, how would one go about using this on a raspberry pi? Would you consider adding a container that would work on arm?

Thank you and sorry for the noob question.

**Comment by ipsingh06** [comment]
This is something I'm taking a look at currently.

**Comment by L4yer** [comment]
That would be awesome.

**Comment by chubs2020** [comment]
Second this, would be amazing. I'm using my Pi 4 8GB and it is working well, except for bringing content home (when I don't have root).

**Comment by ipsingh06** [comment]
Hi guys. I've created an experimental docker image for armv8 architectures. Please try it out on the raspberry pi using the following docker command:
```bash
docker run -p 8800:8800 ipsingh06/seedsync:multiarch-test
```

And let me know here how well it works. If everything goes well, I will include it in the mainline image.

**Comment by ipsingh06** [comment]
See latest release (v0.8.4) for Raspberry Pi support.
