### ISSUE TITLE
[Request] Temporary Filename 

### ISSUE THREAD

**Issue by Smoz** [ipsingh06/seedsync#6]
This is working nicely. One thing that I use with LFTP is the temporary filename. This makes it so that PVRs like Sonarr/Radarr don't scan the file before it's finished being transferred completely. Could you add that as an option in the settings menu? I have my files append ".lftp" at the end, then once the transfer is complete it removes it.

set xfer:use-temp-file yes
set xfer:temp-file-name *.lftp

**Comment by ipsingh06** [comment]
Added in v0.5. Take a look at the Settings page for "Rename unfinished/downloading files".
