### ISSUE TITLE
Possible problem with locale

### ISSUE THREAD

**Issue by s0b** [ipsingh06/seedsync#66]
Today I installed SeedSync in an Unraid server through the Docker image. After filling the configuration of SeedSync in the Settings page, it wasn't able to connect to the remote server. This is the log output:

```
2020/07/31 20:38:01 - INFO - RemoteScanner.RemoteScanner - Installing local:/app/scanfs to remote:/mnt/xxx/scanfs

2020/07/31 20:38:01 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command: scp -q -P 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -o PubkeyAuthentication=no /app/scanfs xxx:/mnt/xxx/scanfs

2020/07/31 20:38:05 - DEBUG - LocalScanner - Running a scan

2020/07/31 20:38:05 - DEBUG - LocalScanner - Scan took 0.010s

2020/07/31 20:38:09 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Return code: 0

2020/07/31 20:38:09 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command took 7.590s

2020/07/31 20:38:09 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command: ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -o PubkeyAuthentication=no xxx "'/mnt/xxx/scanfs' '/mnt/xxx/files'"

2020/07/31 20:38:15 - DEBUG - LocalScanner - Running a scan

2020/07/31 20:38:15 - DEBUG - LocalScanner - Scan took 0.010s

2020/07/31 20:38:15 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob Traceback (most recent call last):
  File "/app/python/common/job.py", line 44, in run
    self.execute()
  File "/app/python/controller/controller_job.py", line 29, in execute
    self.__controller.process()
  File "/app/python/controller/controller.py", line 199, in process
    self.__propagate_exceptions()
  File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
    self.__remote_scan_process.propagate_exception()
  File "/app/python/common/app_process.py", line 124, in propagate_exception
    raise exc.re_raise()
  File "/app/python/common/app_process.py", line 30, in re_raise
    raise self.ee.with_traceback(self.tb)
  File "/app/python/common/app_process.py", line 87, in run
    self.run_loop()
  File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
    files = self.__scanner.scan()
  File "/app/python/controller/scan/remote_scanner.py", line 79, in scan
    recoverable=False
controller.scan.scanner_process.ScannerError: An error occurred while scanning the remote server: 'Invalid pickled data'.

2020/07/31 20:38:15 - DEBUG - seedsync.ControllerJob - Calling cleanup for ControllerJob

2020/07/31 20:38:15 - DEBUG - seedsync.Controller - Exiting controller

2020/07/31 20:38:15 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Return code: 0

2020/07/31 20:38:15 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command took 6.444s

2020/07/31 20:38:15 - ERROR - RemoteScanner.RemoteScanner - Unpickling error: unpickling stack underflow b'bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)\n\x80\x03]q\x00csystem.file\nSystemFile\nq\x01)\x81q\x02}q\x03(X\x11\x00\x00\x00_SystemFile__nameq\x04X\x03\x00\x00\x00asdq\x05X\x11\x00\x00\x00_SystemFile__sizeq\x06K\x00X\x13\x00\x00\x00_SystemFile__is_dirq\x07\x89X\x1e\x00\x00\x00_SystemFile__timestamp_createdq\x08NX\x1f\x00\x00\x00_SystemFile__timestamp_modifiedq\tcdatetime\ndatetime\nq\nC\n\x07\xe4\x07\x1f\x10\x16\x12\x01\x94\xfbq\x0b\x85q\x0cRq\rX\x15\x00\x00\x00_SystemFile__childrenq\x0e]q\x0fuba.'

2020/07/31 20:38:15 - DEBUG - RemoteScanner - Process caught an exception

2020/07/31 20:38:15 - ERROR - seedsync - Caught exception Traceback (most recent call last):
  File "/app/python/seedsync.py", line 162, in run
    controller_job.propagate_exception()
  File "/app/python/common/job.py", line 77, in propagate_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/app/python/common/job.py", line 44, in run
    self.execute()
  File "/app/python/controller/controller_job.py", line 29, in execute
    self.__controller.process()
  File "/app/python/controller/controller.py", line 199, in process
    self.__propagate_exceptions()
  File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
    self.__remote_scan_process.propagate_exception()
  File "/app/python/common/app_process.py", line 124, in propagate_exception
    raise exc.re_raise()
  File "/app/python/common/app_process.py", line 30, in re_raise
    raise self.ee.with_traceback(self.tb)
  File "/app/python/common/app_process.py", line 87, in run
    self.run_loop()
  File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
    files = self.__scanner.scan()
  File "/app/python/controller/scan/remote_scanner.py", line 79, in scan
    recoverable=False
controller.scan.scanner_process.ScannerError: An error occurred while scanning the remote server: 'Invalid pickled data'.

2020/07/31 20:38:16 - DEBUG - ActiveScanner - Process received terminate flag

2020/07/31 20:38:16 - DEBUG - ActiveScanner - Exiting process

2020/07/31 20:38:17 - DEBUG - ExtractProcess - Process received terminate flag

2020/07/31 20:38:17 - DEBUG - seedsync.Controller.MPLogger - Stopped listener thread

2020/07/31 20:38:17 - INFO - seedsync.Controller - Exited controller 
```

According to the log, seems like SeedSync doesn't work well with the locale in the remote server.

The locale in the container is `C.UTF-8` (as stated in the Dockerfile). But the locale in the remote server is also `C.UTF-8`, so I'm lost on this.

Can you see something that I'm missing?

**Comment by quadcom** [comment]
Moved to a new seedbox and now I'm running into this problem too.

Found this online and I'm wondering if this is something we do to the docker container or is it something that I need to bring up to the seedbox host.

https://askubuntu.com/questions/454260/how-to-solve-locale-problem

**Comment by quadcom** [comment]
So I took the LC_ALL:C.UTF-8 and LANG:C.UTF-8 out of the environment variables to see if that changed anything. I was thinking that if SS doesn't specify those maybe it will just use whatever the seedbox server uses.

Here's the action in the logs.

********************************************************************************
2020/08/05 22:08:10 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Return code: 0
2020/08/05 22:08:10 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command took 1.517s
2020/08/05 22:08:10 - INFO - RemoteScanner.RemoteScanner - Installing local:/app/scanfs to remote:/files/seedsync/scanfs
2020/08/05 22:08:10 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command: scp -q -P 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -o PubkeyAuthentication=no /app/scanfs quadcom@tethys.whatbox.ca:/files/seedsync/scanfs
2020/08/05 22:08:11 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2020/08/05 22:08:13 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Return code: 1
2020/08/05 22:08:13 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command took 2.598s
2020/08/05 22:08:13 - WARNING - RemoteScanner.RemoteScanner.Sshcp - Command failed: 'scp: /files/seedsync/scanfs: No such file or directory - '
2020/08/05 22:08:13 - ERROR - RemoteScanner.RemoteScanner - Caught scp exception Traceback (most recent call last): File "/app/python/controller/scan/remote_scanner.py", line 117, in _install_scanfs remote_path=self.__remote_path_to_scan_script) File "/app/python/ssh/sshcp.py", line 198, in copy args=" ".join(args) File "/app/python/ssh/sshcp.py", line 138, in __run_command raise SshcpError(sp.before.decode().strip()) ssh.sshcp.SshcpError: scp: /files/seedsync/scanfs: No such file or directory
2020/08/05 22:08:13 - DEBUG - RemoteScanner - Process caught an exception
2020/08/05 22:08:13 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 51, in scan
self._install_scanfs()
File "/app/python/controller/scan/remote_scanner.py", line 122, in _install_scanfs
recoverable=False
controller.scan.scanner_process.ScannerError: An error occurred while installing scanner script to remote server: 'scp: /files/seedsync/scanfs: No such file or directory'.
2020/08/05 22:08:13 - DEBUG - seedsync.ControllerJob - Calling cleanup for ControllerJob
2020/08/05 22:08:13 - DEBUG - seedsync.Controller - Exiting controller
2020/08/05 22:08:13 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "/app/python/seedsync.py", line 162, in run
controller_job.propagate_exception()
File "/app/python/common/job.py", line 77, in propagate_exception
raise exc_info[1].with_traceback(exc_info[2])
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 51, in scan
self._install_scanfs()
File "/app/python/controller/scan/remote_scanner.py", line 122, in _install_scanfs
recoverable=False
controller.scan.scanner_process.ScannerError: An error occurred while installing scanner script to remote server: 'scp: /files/seedsync/scanfs: No such file or directory'.
2020/08/05 22:08:14 - DEBUG - ActiveScanner - Process received terminate flag
2020/08/05 22:08:14 - DEBUG - ActiveScanner - Exiting process
2020/08/05 22:08:15 - DEBUG - ExtractProcess - Process received terminate flag
2020/08/05 22:08:15 - DEBUG - seedsync.Controller.MPLogger - Stopped listener thread
2020/08/05 22:08:15 - INFO - seedsync.Controller - Exited controller
2020/08/05 22:08:15 - DEBUG - seedsync.ControllerJob - Finished cleanup for ControllerJob
2020/08/05 22:08:15 - DEBUG - seedsync.ControllerJob - Thread ControllerJob stopped
2020/08/05 22:08:39 - DEBUG - seedsync - Persisting states to file
2020/08/05 22:09:09 - DEBUG - seedsync - Persisting states to file
****************************************************************************************

scanfs constantly fails to install. I've tried multiple directories and it made no difference.

**Comment by quadcom** [comment]
OK, I figured out a fix. From what I understood, I changed both LC_ALL and LANG to both en_US.UTF-8.

I then caught an error in the path that I had for the scanner script. I had a preceding / at the start of the path. Once I took that out the scanner was installed and everything is working great on the new server!!!!

**Comment by ipsingh06** [comment]
As @quadcom mentioned, this is a remote server issue. The error `bash: warning: setlocale: LC_ALL: cannot change locale` will be thrown if you try to run any script on the server.

@quadcom If I'm understanding your fix correctly, you modified `/etc/environment` to have the following:
```
LC_ALL="en_CA.UTF-8"
LANG="en_CA.UTF-8"
```
Is that correct?

@s0b could you please try this on your remote server as well?

If this is the fix then I will update the documentation.

**Comment by quadcom** [comment]
Correction,

I used en_US.UTF-8 for both vars.

**Comment by s0b** [comment]
@ipsingh06 agree that the problem is the mismatch between the docker container and remote server locales. I can't change the locale in the remote server as its out of my user priviledges. All that I have is regular user in a shared server.

If I'm understanding @quadcom correctly, he is changing manually the locale in his SeedSync docker container to match the remote server locale. From what I know his solution will fail again when the SeedSync container is redeployed unless he loads the /etc/environment file from the host using a volume entry.

I suggest to solve this problem making the locale configurable through an environment variable. What do you think? I can get ready a pull request if you consider this a viable option.

Just as a note, Im using the same seedbox provider than @quadcom ([whatbox](https://whatbox.ca/)) so seem like there will be more people in the same situation.

**Comment by quadcom** [comment]
@s0b  - Those are editable in the environment variables in the Docker container.

![image](https://user-images.githubusercontent.com/7085931/89698832-513ea780-d8f1-11ea-946d-ea55759ceb55.png)

**Comment by s0b** [comment]
@quadcom my bad, your solution is the way to go. I tested it and it's working perfectly.

@ipsingh06 as I expect more users to have this issue, it would be good to have this in the docs.

The issue is solved so I'm closing it. Thanks guys.

**Comment by ipsingh06** [comment]
Thanks a lot guys. I've updated the documentation to reflect your findings.
