### ISSUE TITLE
REQ: Add uploading options for seeding new content

### ISSUE THREAD

**Issue by quadcom** [ipsingh06/seedsync#67]
Ok, possibly a big project but the torrent scene wouldn't exist without new content being posted which ATM requires uploading via an FTP client and building the torrent on the box. SS could be a one-stop-shop tool to speed up workflow.

It would be a nice add if we could define an upload folder in settings and then in the SS UI, be able to choose a folder to UL to the server.

PS. how can we add labels to issues to help keep things clean in here?

**Comment by ipsingh06** [comment]
This would be nice, but the scope for this is too large for SeedSync. For two-way sync, one would be better off using SyncThing or Resilio.
