### ISSUE TITLE
Debian - Seedsync service no longer starting

### ISSUE THREAD

**Issue by UnicodeError** [ipsingh06/seedsync#72]
Seedsync was working with no issues and all of a sudden has stopped working. Restarted box and manually stopped and started the service to no avail. Receiving the following error from systemctl status:

user@box1:~$ sudo systemctl status seedsync.service 
● seedsync.service - Job that runs the SeedSync daemon
   Loaded: loaded (/lib/systemd/system/seedsync.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/seedsync.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Fri 2020-10-09 00:50:26 EDT; 1min 53s ago
  Process: 28346 ExecStart=/usr/lib/seedsync/seedsync --logdir ${HOME}/.seedsync/log -c ${HOME}/.seedsync (code=exited, status=255)
  Process: 28343 ExecStartPre=/bin/mkdir -p ${HOME}/.seedsync/log (code=exited, status=0/SUCCESS)
  Process: 28340 ExecStartPre=/bin/mkdir -p ${HOME}/.seedsync (code=exited, status=0/SUCCESS)
 Main PID: 28346 (code=exited, status=255)

Oct 09 00:50:26 box1 seedsync[28346]:   File "common/persist.py", line 50, in from_file
Oct 09 00:50:26 box1 seedsync[28346]:   File "/usr/lib/python3.7/codecs.py", line 322, in decode
Oct 09 00:50:26 box1 seedsync[28346]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 3: invalid continuation byte
Oct 09 00:50:26 box1 seedsync[28346]: During handling of the above exception, another exception occurred:
Oct 09 00:50:26 box1 seedsync[28346]: Traceback (most recent call last):
Oct 09 00:50:26 box1 seedsync[28346]:   File "seedsync.py", line 386, in <module>
Oct 09 00:50:26 box1 seedsync[28346]: AttributeError: 'NoneType' object has no attribute 'exception'
Oct 09 00:50:26 box1 systemd[1]: seedsync.service: Main process exited, code=exited, status=255/n/a
Oct 09 00:50:26 box1 systemd[1]: seedsync.service: Unit entered failed state.
Oct 09 00:50:26 box1 systemd[1]: seedsync.service: Failed with result 'exit-code'.

Any help or direction you can provide would be greatly appreciated, thanks in advance!

**Comment by ipsingh06** [comment]
@UnicodeError Sorry for the delayed response, been really busy. Were you able to get this sorted out?

**Comment by UnicodeError** [comment]
No worries, I was not, been banging my head against the wall with it to be honest. Any idea what causes this error or suggested rocks I should overturn?

**Comment by ipsingh06** [comment]
I can think of this happening if there is a mismatch between Seedsync version and the scanner script that is installed on the remote server. But a restart of Seedsync should fix it.

**Comment by UnicodeError** [comment]
So far I have attempt a restart manually, rebooted the machine, and have attempted to reinstall SeedSync over itself. How do I verify/remove/update the scanner script on the remote server?

**Comment by quadcom** [comment]
I do believe you are running into the language issue.

As per the docs...

If you receive errors related to locale when connecting to the remote server, then also include the following options.

-e LC_ALL=en_US.UTF-8 -e LANG=en_US.UTF-8

**Comment by UnicodeError** [comment]
Appreciate the input, but isn't that only for docker? I am running SeedSync on a standalone ubuntu server. 

I have to figure out what is the scanner directory on the remote server. Unfortunately it was easier when I had access to the GUI.

**Comment by ipsingh06** [comment]
What is the output of this command on both the local and remote servers?
`locale`

**Comment by UnicodeError** [comment]
Local - 

user@box1:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=


Remote -

[box2 ~] locale
LANG=en_GB.utf8
LANGUAGE=
LC_CTYPE="en_GB.utf8"
LC_NUMERIC="en_GB.utf8"
LC_TIME="en_GB.utf8"
LC_COLLATE="en_GB.utf8"
LC_MONETARY="en_GB.utf8"
LC_MESSAGES="en_GB.utf8"
LC_PAPER="en_GB.utf8"
LC_NAME="en_GB.utf8"
LC_ADDRESS="en_GB.utf8"
LC_TELEPHONE="en_GB.utf8"
LC_MEASUREMENT="en_GB.utf8"
LC_IDENTIFICATION="en_GB.utf8"
LC_ALL=


Might be on to something here...

**Comment by ipsingh06** [comment]
Your locale looks fine actually. I believe this error has to do with special characters in file names that SeedSync is having trouble parsing. Could you please send me two files from your config directory: `controller.persist` and `autoqueue.persist`. You can look up my email in my profile.

**Comment by ipsingh06** [comment]
@UnicodeError I have implemented a fix in the newest version that should prevent this error. Please try the latest version v0.8.6. You will have to remove your settings files in `~/.seedsync` and start fresh because your existing files are corrupted. Please post back if you still run into issues.

**Comment by UnicodeError** [comment]
I apologize for the delayed response, thank you so much for the fix, I reinstalled the program and deleted the setting files as instructed everything is working now thank you again for your work on this project. It is such a time saver.
