### ISSUE TITLE
Details shows "Not available" and doesn't list file names of what is being downloaded

### ISSUE THREAD

**Issue by Wh1t3Rose** [ipsingh06/seedsync#76]
![image](https://user-images.githubusercontent.com/4251482/99923856-a8805080-2d05-11eb-87d2-bc7ff96c67a5.png)

**Comment by quadcom** [comment]
Change your target location to DL from within the Movies folder. It will then DL the folder inside separately and show correct stats ad details.

**Comment by Wh1t3Rose** [comment]
Ok that isn't really ideal though. For my situation the script is pulling files from a Seedbox and the download client on that box sends everything to a Finished/TV or a Finished/Movies or a Finished/Games. So naturally I have the script pointed to the Finished directory. 

Sounds like either their needs to be a way to specify several remote Dirs in Settings or just have my Seedbox throw all my Movies and Games and TV in one single folder (crappy solution IMO)

**Comment by quadcom** [comment]
Feel free to fork this project and build it out as you see fit.

Or, post a nicely worded feature request. Maybe ipsingh might agree and put it in.

**Comment by ipsingh06** [comment]
As quadcom said, SeedSync only works at the top-level directory for now. Multiple remote directories would require a lot of work and is not planned for the near term.
