### ISSUE TITLE
SeedSync v0.8.4 keep crashing when resuming download

### ISSUE THREAD

**Issue by SkinnyV** [ipsingh06/seedsync#78]
I have been running seedsync v0.8.4 without issue as a docker on my unraid file server for the past few days. It has been syncing a big 1.85tb folder from my seedbox since 2-3 days but started crashing yesterday. When seedsync crash, the whole docker seem to shut down and need to be restarted manually. Now, seedsync will consistently crash almost right away if I try to resume that folder download. Any idea what could be causing this? I tried rebooting my unraid server with not change. I seem to be able to start new download without it crashing. Here are the log showing the crash I am referring to, I edited out my username and seedbox server address and removed a few line listing most of of the folder that I have on my server but is otherwise untouched. Thank you for your help!

2020/12/15 12:42:17 - INFO - seedsync.Controller - Received command Action.QUEUE for file TV
2020/12/15 12:42:32 - INFO - seedsync.ServerActionHandler - Received a restart action
2020/12/15 12:42:32 - INFO - seedsync - Exiting Seedsync
2020/12/15 12:42:38 - DEBUG - seedsync.ControllerJob - Thread ControllerJob started
2020/12/15 12:42:38 - DEBUG - seedsync.WebAppJob - Thread WebAppJob started
2020/12/15 12:42:38 - DEBUG - seedsync.ControllerJob - Calling setup for ControllerJob
2020/12/15 12:42:38 - DEBUG - seedsync.WebAppJob - Calling setup for WebAppJob
2020/12/15 12:42:38 - DEBUG - seedsync.Controller - Starting controller
2020/12/15 12:42:38 - DEBUG - seedsync.WebAppJob - Finished setup for WebAppJob
2020/12/15 12:42:38 - DEBUG - seedsync.Controller.MPLogger - Started listener thread
2020/12/15 12:42:38 - DEBUG - ActiveScanner - Started process
2020/12/15 12:42:38 - DEBUG - seedsync.ControllerJob - Finished setup for ControllerJob
2020/12/15 12:42:38 - DEBUG - LocalScanner - Started process
2020/12/15 12:42:38 - DEBUG - LocalScanner - Running a scan
2020/12/15 12:42:38 - DEBUG - RemoteScanner - Started process
2020/12/15 12:42:38 - DEBUG - RemoteScanner - Running a scan
2020/12/15 12:42:38 - DEBUG - ExtractProcess - Started process
2020/12/15 12:42:38 - DEBUG - ExtractDispatch - Started worker thread
2020/12/15 12:42:38 - DEBUG - RemoteScanner.RemoteScanner - Local scanfs md5sum = 5b74ccc713ce6a48bae48c9ee3b9ed23
2020/12/15 12:42:38 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command: ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -o PubkeyAuthentication=no users123@tobias.seedbox.com "md5sum /tmp/scanfs | awk '{print $1}' || echo"
2020/12/15 12:42:40 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Return code: 0
2020/12/15 12:42:40 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command took 1.450s
2020/12/15 12:42:40 - INFO - RemoteScanner.RemoteScanner - Skipping remote scanfs installation: already installed
2020/12/15 12:42:40 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command: ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -o PubkeyAuthentication=no users123@tobias.seedbox.com "'/tmp/scanfs' '/home12/users123/downloads/'"
2020/12/15 12:42:41 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2020/12/15 12:42:42 - DEBUG - LocalScanner - Scan took 3.366s
2020/12/15 12:42:42 - DEBUG - seedsync.Controller.Model - LftpModel: Adding file 'youtube-dl'
2020/12/15 12:42:42 - DEBUG - seedsync.Controller.Model - LftpModel: Adding file 'IsoBuster'
2020/12/15 12:42:42 - DEBUG - seedsync.Controller.Model - LftpModel: Adding file 'AllData'
2020/12/15 12:42:42 - DEBUG - seedsync.Controller.Model - LftpModel: Adding file 'TV'
2020/12/15 12:42:46 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Return code: 0
2020/12/15 12:42:46 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command took 6.304s
2020/12/15 12:42:47 - DEBUG - RemoteScanner - Scan took 8.187s
2020/12/15 12:42:48 - DEBUG - LocalScanner - Running a scan
2020/12/15 12:42:51 - DEBUG - LocalScanner - Scan took 2.803s
2020/12/15 12:42:54 - DEBUG - seedsync.Controller.Model - LftpModel: Adding file 'watch'
2020/12/15 12:42:54 - DEBUG - seedsync.Controller.Model - LftpModel: Adding file 'Rick.and.Morty'
2020/12/15 12:42:58 - DEBUG - LocalScanner - Running a scan
2020/12/15 12:43:00 - INFO - seedsync.Controller - Received command Action.QUEUE for file TV
2020/12/15 12:43:01 - DEBUG - LocalScanner - Scan took 3.015s
2020/12/15 12:43:08 - DEBUG - seedsync.Controller.Model - LftpModel: Updating file 'TV'
2020/12/15 12:43:08 - DEBUG - LocalScanner - Running a scan
2020/12/15 12:43:08 - DEBUG - RemoteScanner - Running a scan
2020/12/15 12:43:08 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command: ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -o PubkeyAuthentication=no users123@tobias.seedbox.com "'/tmp/scanfs' '/home12/users123/downloads/'"
2020/12/15 12:43:09 - DEBUG - seedsync - Persisting states to file
2020/12/15 12:43:11 - DEBUG - LocalScanner - Scan took 2.212s
2020/12/15 12:43:16 - DEBUG - seedsync.Controller.Model - LftpModel: Updating file 'TV'
2020/12/15 12:43:17 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Return code: 0
2020/12/15 12:43:17 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command took 8.775s
2020/12/15 12:43:17 - DEBUG - RemoteScanner - Scan took 8.911s
2020/12/15 12:43:18 - DEBUG - LocalScanner - Running a scan
2020/12/15 12:43:21 - DEBUG - LocalScanner - Scan took 2.477s
2020/12/15 12:43:24 - DEBUG - seedsync.Controller.Model - LftpModel: Updating file 'TV'
2020/12/15 12:43:28 - DEBUG - LocalScanner - Running a scan
2020/12/15 12:43:31 - DEBUG - LocalScanner - Scan took 2.246s
2020/12/15 12:43:34 - DEBUG - seedsync.Controller.Model - LftpModel: Updating file 'TV'
2020/12/15 12:43:38 - DEBUG - LocalScanner - Running a scan
2020/12/15 12:43:38 - DEBUG - RemoteScanner - Running a scan
2020/12/15 12:43:38 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command: ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -o PubkeyAuthentication=no users123@tobias.seedbox.com "'/tmp/scanfs' '/home12/users123/downloads/'"
2020/12/15 12:43:39 - DEBUG - seedsync - Persisting states to file
2020/12/15 12:43:41 - DEBUG - LocalScanner - Scan took 2.579s
2020/12/15 12:43:43 - DEBUG - seedsync.Controller.Model - LftpModel: Updating file 'TV'
2020/12/15 12:43:46 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Return code: 0
2020/12/15 12:43:46 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command took 7.578s
2020/12/15 12:43:46 - DEBUG - RemoteScanner - Scan took 7.776s
2020/12/15 12:43:48 - DEBUG - LocalScanner - Running a scan
2020/12/15 12:43:51 - DEBUG - LocalScanner - Scan took 2.262s
2020/12/15 12:43:52 - DEBUG - seedsync.Controller.Model - LftpModel: Updating file 'TV'
2020/12/15 12:43:53 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 202, in process
self.__update_model()
File "/app/python/controller/controller.py", line 295, in __update_model
lftp_statuses = self.__lftp.status()
File "/app/python/lftp/lftp.py", line 320, in status
out = self.__run_command("jobs -v")
File "/app/python/lftp/lftp.py", line 97, in wrapper
return method(inst, *args, **kwargs)
File "/app/python/lftp/lftp.py", line 133, in __run_command
out = self.__process.before.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3083: invalid continuation byte
2020/12/15 12:43:53 - DEBUG - seedsync.ControllerJob - Calling cleanup for ControllerJob
2020/12/15 12:43:53 - DEBUG - seedsync.Controller - Exiting controller
2020/12/15 12:43:53 - INFO - seedsync - Exiting Seedsync
2020/12/15 12:43:53 - DEBUG - ActiveScanner - Process received terminate flag
2020/12/15 12:43:53 - DEBUG - ActiveScanner - Exiting process

**Comment by quadcom** [comment]
how many simultaneous transfers are you doing?

I've noticed that if I have any more than 1 transfer at a time with 10 threads it causes problems. If you have multiple files transferring perhaps trying to limit the connections per file to 1 and see if that makes a difference.

**Comment by ipsingh06** [comment]
I believe SeedSync is having trouble with special characters in the name of the folder. Could you please provide the name of the folder you are trying to sync (feel free to email it to me - see my profile for address).

**Comment by SkinnyV** [comment]
There is indeed a bunch of special characters, Sending you the list.

**Comment by ipsingh06** [comment]
@SkinnyV My email response to you isn't going through. Could you please tell me which of those names was causing it to crash?

**Comment by SkinnyV** [comment]
The software doesn't give me anymore information than what I have in the log. Is there a way I can figure that out if it is not stated in the log?

**Comment by ipsingh06** [comment]
@SkinnyV It's all good, I've been able to reproduce this issue now. I am working on a fix.

**Comment by SkinnyV** [comment]
Testing out the new version right now, seem to no longer be crashing! Thanks!

**Comment by ipsingh06** [comment]
Great to haer @SkinnyV , thanks for the quick feedback!
