### ISSUE TITLE
not downloading 0.8.4

### ISSUE THREAD

**Issue by HarleyL7** [ipsingh06/seedsync#79]
installed using the deb package and seems to be running fine. but when I go to the dashboard it shows downloading with an eta of ? and 0%. 

anyone run into this problem before?
![seedsync](https://user-images.githubusercontent.com/41248030/102682436-eb530e00-4175-11eb-9cf2-9c09ef44d879.JPG)

**Comment by HarleyL7** [comment]
Logs below with debug mode one. I hope these help
![seedsync logs](https://user-images.githubusercontent.com/41248030/102682486-61f00b80-4176-11eb-85ba-da6452398b64.JPG)

**Comment by quadcom** [comment]
Show your config page too

**Comment by HarleyL7** [comment]
![Screenshot_20201219-105102_Chrome.jpg](https://user-images.githubusercontent.com/41248030/102693377-2f7ef680-41e8-11eb-94f3-6e4de75f8d98.jpg)

**Comment by HarleyL7** [comment]
So I did notice this line this morning. "stream connection stopped by client" 
![Screenshot_20201219-105301_Chrome.jpg](https://user-images.githubusercontent.com/41248030/102693418-6b19c080-41e8-11eb-8524-035ab45ddfbb.jpg)

**Comment by HarleyL7** [comment]
So just to update this, I have no idea what's wrong with it. But I was able to get it working on the docker version.

**Comment by quadcom** [comment]
Server script path should be a location on the remote server not the seedsync box. 

Try some connection settings that aren't going to nuke your seedbox. 

Max dl:1
Max tot Conn:10
Max Conn p/file:10
Max par/dir:1

Check off rename so it's clear what is finishing and what isn't

The power of lftp is the threaded approach. Being able to dl one large file using multiple threads. Use all the avail threads dl'ing each file one at a time and things should go quicker over all.

Think about it this way. If you have one 3gb file with a handful of smaller files. You max each file at 4 connections with 16 total threads. Each file will only ever get 4 connection no matter the size of the file. The handful of smaller files will be finished while the larger file will be capped at 4 threads. Do one file at a time with 10 threads each with a max of 10 threads total and each file will do at max speed.  

The setting you have there is attempting to use over 40 threads at once but then caps it at 16 threads total. Most boxes will cap at around 10 or so threads(sftp logins) at once.

I've also seen SS kind of get confused when multiple files are dl'ing at the same time and connections get reset. This may be on the server side and not SS but if you do one file at a time I've never had a problem.

**Comment by HarleyL7** [comment]
> Server script path should be a location on the remote server not the seedsync box. 
> 
> Try some connection settings that aren't going to nuke your seedbox. 
> 
> Max dl:1
> Max tot Conn:10
> Max Conn p/file:10
> Max par/dir:1
> 
> Check off rename so it's clear what is finishing and what isn't
> 
> The power of lftp is the threaded approach. Being able to dl one large file using multiple threads. Use all the avail threads dl'ing each file one at a time and things should go quicker over all.
> 
> Think about it this way. If you have one 3gb file with a handful of smaller files. You max each file at 4 connections with 16 total threads. Each file will only ever get 4 connection no matter the size of the file. The handful of smaller files will be finished while the larger file will be capped at 4 threads. Do one file at a time with 10 threads each with a max of 10 threads total and each file will do at max speed.  
> 
> The setting you have there is attempting to use over 40 threads at once but then caps it at 16 threads total. Most boxes will cap at around 10 or so threads(sftp logins) at once.
> 
> I've also seen SS kind of get confused when multiple files are dl'ing at the same time and connections get reset. This may be on the server side and not SS but if you do one file at a time I've never had a problem.

Yeah, that's server script is on the remote server. It's the same style of path lol so a little confusing. 

So I was just looking for settings to actually nuke my connection and download fast lol do you have any of those?

Idk why it wouldn't work with the Deb package and works with docker. I'm guessing it's permission errors, just not showing up on the logs

**Comment by ipsingh06** [comment]
@HarleyL7 , glad you were able to get it working with the docker image. The deb version uses LFTP installed on your system which may have been failing for some unknown reason. Please post back if you run into any further problems.
