### ISSUE TITLE
Seedsync without ssh

### ISSUE THREAD

**Issue by eephyne** [ipsingh06/seedsync#82]
Hello

Not a bug at all, but is this possible to use seedsync withot ssh access ? (only ftp)
I currently use lftp script running on cron to sync, so its possible, but i'd really like to have a ui to check current status.

If its not possible right now, is it something that could be added to roadmap or not at all ?

Thanks :)

**Comment by quadcom** [comment]
I'm a little confused as to what you want to accomplish.

SS will log into SSH and download whatever it finds in the target download DIR. It's not a configurable UI to watch other programs' connections or transfers.

Is the CRON job you are running uploading content to the server or is the CRON job downloading files from the server?

If you're downloading files using the CRON job, SS could be used in its place. Your CRON job is going to run on a schedule where SS will only initiate a download when new files are detected. 

Keep in mind that SS is a one-way sync. It does not upload files back to the server if files or folders are added to the download DIR.

**Comment by eephyne** [comment]
I use it do sync one way, it run on my local server to retrieve files from the remote one.

**Comment by quadcom** [comment]
So in that case, SS could replace your CRON job entirely.

**Comment by eephyne** [comment]
How can I do that  ?

**Comment by quadcom** [comment]
All of the instructions are posted in the documentation (https://ipsingh06.github.io/seedsync/).

Determine your platform and follow along with the instructions. If you can set up a CRON job on your server you should be able to pull this off.

**Comment by ipsingh06** [comment]
@eephyne Seedsync requires SSH to fetch the file sizes from the remote server. There is currently no plan to support SSH-less connections.
