### ISSUE TITLE
Permission Error when installing

### ISSUE THREAD

**Issue by ghost** [ipsingh06/seedsync#86]
Linux Mint 20 
Running newest version in Docker
Hello World docker runs fine
When I install I get the following error:
```
Traceback (most recent call last):
  File "/app/python/seedsync.py", line 378, in <module>
    seedsync = Seedsync()
  File "/app/python/seedsync.py", line 60, in __init__
    config.to_file(self.config_path)
  File "/app/python/common/persist.py", line 53, in to_file
    with open(file_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/config/settings.cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/python/seedsync.py", line 386, in <module>
    Seedsync.logger.exception("Caught exception")
AttributeError: 'NoneType' object has no attribute 'exception'
```

**Comment by ghost** [comment]
This problem might be related to the settings.cfg but I have no idea what to put into the settings.cfg. I cant find any documentation. 
Can anyone maybe share where I can find documentation on what to put into the settings.cfg?

**Comment by ipsingh06** [comment]
Please take a look at the installation instructions here: https://ipsingh06.github.io/seedsync/install/#docker-image-linuxubuntu-raspberry-pi

**Comment by jamauai** [comment]
Followed the doc and still get the same error using latest Docker image.

![Screen Shot 2021-02-01 at 3 02 50 AM](https://user-images.githubusercontent.com/16515595/106462649-78a6a500-643a-11eb-8bba-b156ae2e28a0.png)

**Comment by TaakoMagnusen** [comment]
same error here. Is this project abandoned?

**Comment by quadcom** [comment]
This error is due to the permissions on the Docker host not being able to access the config file.

1. Where are you installing this? Synology?
2. Have you checked the UID and GID of the user on the host system that will access the config files DIR?
3. Did you set the GID and UID in the docker container VARs?

I don't believe that this project has been abandoned. It is a side project that @ipsingh06 wrote to solve his own problem. I have not heard from him for a while. Life does get in the way. I do understand that this is not a high priority for him though. It does need some tweaks here and there but all in all, it does work well (at least for me it does).

**Comment by quadcom** [comment]
Installing on Synology comes with its own issues. These are not related to Seedsync itself but with how Synology manages Docker containers.

***Start New Seedsync Container - Run this from an SSH session to your Synology***

docker pull ipsingh06/seedsync
sudo docker run --name SeedSync -p 8802:8800 -v /volume3/Sync/Seedbox/z-config:/config -v /volume3/Sync/Seedbox/1-Incoming:/incoming --user {UID}:{GID} ipsingh06/seedsync:latest


***Clear out Synology Docker Containers When Stuck - Run this from an SSH session to your Synology if you are having issues building the container***

rm /tmp/DSMTaskMgr/@administrators/SYNO_DOCKER_IMAGE_PULL*

**Comment by TaakoMagnusen** [comment]
thanks for responding. Im trying to install the docker on unRaid. All im setting is the port, the /config, and the /downloads map. the directories all exist already. im not setting the UID/GUID. The host shouldnt have an issue accessing the /config mapped dir, at least all my other docker containers dont have issue.

heres the end resulting docker command

```
docker run
  -d
  --name='seedsync'
  --net='bridge'
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Omega"
  -e HOST_CONTAINERNAME="seedsync"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8800]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/seedsync.png'
  -p '8800:8800/tcp'
  -v '/mnt/user/appdata/seedsync/':'/config':'rw'
  -v '/mnt/user/downloads/seedbox/':'/downloads':'rw' 'ipsingh06/seedsync'

```

**Comment by TaakoMagnusen** [comment]
okay i figured i *almost* out. The docker container was not creating a settings.cfg.

First i did `touch /mnt/user/appdata/seedsync/settings.cfg` and then when i tried booting the container it said some other error about the cfg not having a "general" section.

I found someone elses cfg on another issue and just copied it into the settings.cfg, and it booted. So it seems like the docker  was not able to or chose not to create the initial settings.cfg

Then when i stopped the container i got an error

```

    shutil.copy(file_path, backup_path)
  File "/usr/local/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/config/settings.cfg.1.bak'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/python/seedsync.py", line 386, in <module>
    Seedsync.logger.exception("Caught exception")
AttributeError: 'NoneType' object has no attribute 'exception'
Traceback (most recent call last):
  File "/app/python/seedsync.py", line 158, in run
    self.persist()
  File "/app/python/seedsync.py", line 210, in persist
    self.controller_persist.to_file(self.controller_persist_path)
  File "/app/python/common/persist.py", line 53, in to_file
    with open(file_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/config/controller.persist'
```

so there is still some issue...

**Comment by TaakoMagnusen** [comment]
okay, instead of setting PUID and GUID vars i just added parameter `-u 99:100` to the docker args and its working

**Comment by quadcom** [comment]
I am using UnRaid as well now.  Any reason why you didn't use the app in the UnRaid market?

Worked great for me.

**Comment by TaakoMagnusen** [comment]
i am using the unraid app market template, it didnt work out of the box  (i'm on unraid 6.11 if it matters), i had to ad the `-u 99:100` to the extra parameters section of the docker template to get it to boot.

btw off topic, but is there a way to get sync only specific folders? I enabled auto-queue pattern match and set one to `series/*` and one to `movies/*` but its not syncing those directories.
