### ISSUE TITLE
Can't find config file in Ubuntu 18.04 (SSH Docker instance on seedbox)

### ISSUE THREAD

**Issue by jamauai** [ipsingh06/seedsync#87]
Where is the config file located in Ubuntu? Running SSH Docker instance on a seedbox and was able to install SeedSync via .DEB file, but can't seem to find the settings file. Would like to be able to change the web UI port from 8800 to something else.

**Comment by quadcom** [comment]
I'm a little confused. If I understand you, you've installed seedsync on a seedbox?

**Comment by jamauai** [comment]
It's an Ubuntu Docker container on a seedbox. I guess the question simply should have been, where is the Linux config file stored?

**Comment by quadcom** [comment]
can you explain your use case for putting SS on a Seedbox?

Normally, SS is used to pull data FROM a seedbox to your local destination. Most people, including myself, use SS in a docker container running on a Synology NAS that we have in our home.

Having SS on the Seedbox is going to pull data ONTO the seedbox. Is this what you had intended to have happen?

**Comment by quadcom** [comment]
in answer to your question. You decide where the config file is located. Your container build script is going to define the config directory on the host system. That is the DIR mapping.

You can set the port mapping and DIR mappings in the container run command

docker run \
   -p 8800:8800 \
   -v <downloads directory>:/downloads \
   -v <config directory>:/config \
   ipsingh06/seedsync

https://ipsingh06.github.io/seedsync/install/

**Comment by jamauai** [comment]
Doh! Well this is embarrassing. I've been using Resilio for so long I thought for a moment I needed SS on both sides. My apologies! Thank you for all your help.
