### ISSUE TITLE
Add reverse proxy support

### ISSUE THREAD

**Issue by hxcadam** [ipsingh06/seedsync#9]
Can you add a base url option like sonarr/radarr etc so nginx reverse proxy will work?

**Comment by hxcadam** [comment]
I'm not very versed in reverse proxy I just copied a config online and have been replicating with the base urls.  I tried that link but it doesn't work.  I'll try to look into it further.

**Comment by STX2k** [comment]
Any Update? for Reverse Support?

**Comment by nitrobass24** [comment]
This does support reverse proxy. I have it setup the following way. 

Cloudflare DNS/HTTPS-->Firewall/Router-->port_fwd443-->Synology Reverse Proxy-->Docker Container

**Comment by ipsingh06** [comment]
Closing this issue for now. Please create a new issue if this is still a problem. Thanks.
