### ISSUE TITLE
ssh.sshcp.SshcpError: Unknown error - ***: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

### ISSUE THREAD

**Issue by undodgeable** [ipsingh06/seedsync#98]
I'm almost there getting SeedSync up and running on my Synology, just getting the following error displayed at the top of the GUI (seedbox details replaced with asterisks below): 

An error occurred while installing scanner script to remote server: 'Unknown error - ***: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).'.

I have the 'Server Script Path' set to a folder on my seedbox which I have write permissions for.
Any ideas/suggestions would be greatly appreciated...

**Comment by quadcom** [comment]
Not sure about you but I'm not the biggest Linux geek out there so I've never really had much success using SSH keys. I've always just stuck with username and password.

It looks to me like you are using keys here. Could you try using uname and pword and see if this starts working for you. If it does then it's pretty easy to determine its a key issue.

**Comment by undodgeable** [comment]
Thanks for the reply.  I am actually using username and password and left the 'Use password-less key-based authentication' box unchecked on the GUI?
Is there anything else I need to set, to force username and password?

**Comment by undodgeable** [comment]
I just deleted and recreated the SeedSync container in docker (via the run command settings from one of your previous posts, which helped me get to where I am now, thanks), and in the settings page of the SeedSync GUI, I filled out all the highlighted fields but left the 'Server Script Path' cell as default value (/tmp), and now I get the following error: -

An error occurred while installing scanner script to remote server: 'Unknown error - mkdir: cannot create directory ‘/home/seedsync’: Permission denied Could not create directory '/home/seedsync/.ssh'. undodgeable@185.149.90.94: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).'.

Any ideas?

**Comment by undodgeable** [comment]
After a bit more testing, I can confirm I don't have write permissions to the /home directory folder on my seedbox, only the /home/user directory.  Changing the 'Server Script Path' under the SeedSync GUI settings to /home/user makes no difference, I still get the following error:

'Unknown error - mkdir: cannot create directory ‘/home/seedsync’: Permission denied Could not create directory '/home/seedsync/.ssh'. undodgeable@185.149.90.94: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

I'm out of ideas...

**Comment by undodgeable** [comment]
Now sorted and working!
Issue was a bit of a schoolboy error, my seedbox was using a different SSH port than 22, changed the SSH port to the correct one via the SeedSync GUI, and bam, all working!

**Comment by quadcom** [comment]
Yaaay
